server:
  port: 81
spring:
  datasource:
    url:  jdbc:mysql://192.168.50.52:3306/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    name: wiki
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc123++
  main:
    allow-circular-references: true
  redis:
    host: 192.168.50.52
    port: 6379
    password: weiwei91


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.wei.wiki.mapper: trace